### ISSUE TITLE
storage service limitations, dependencies

### ISSUE THREAD

**Issue by sdetweil** [u-blox/c209-aoa-tag#10]
I want to save the eddystone info my AT command sets,  into storage. like the transmit power. 

is there any doc on the storage service?

**Comment by perssonmagnus** [comment]
Hi,

You mean the same as is done with the TxPower in https://github.com/u-blox/c209-aoa-tag/blob/master/src/storage.c?
The NVS of Zephyr is described in the Zephyr doc, https://docs.zephyrproject.org/latest/reference/storage/nvs/nvs.html?highlight=nvs_write#api-reference.

**Comment by sdetweil** [comment]
yes, thanks.
