### ISSUE TITLE
BLE Direction Finding - no extended advertisments?

### ISSUE THREAD

**Issue by trembel** [u-blox/c209-aoa-tag#11]
Dear all,
I want to create my own tag, able to be detected by the C211.
However, it seems that the C211 only detects the CTE of Eddystone Beacons, as specified in your source code. Do I have the correct understanding, that it is only able to detect the CTE directly following the legacy advertisment, instead of detecting the CTE at the end of an extended advertisment packet? If yes, are there plans to change the C211 to support the extended advertisment format, containing the CTE?

Best,
trembel

**Comment by perssonmagnus** [comment]
Hello,

To quite [this answer](https://portal.u-blox.com/s/question/0D52p0000C3ZkLCCQ0/eddystone-beacons-with-appended-withconstant-tone-extensionscte) on the u-blox portal: 

"The current version of the u-connectLocate SW and the C209 tag SW utilizes the Eddystone Beacon format with non-periodic advertising and an appended Contant Tone Extension, as described in https://github.com/u-blox/c209-aoa-tag#adding-the-cte-to-advertise-packets.

A coming release of the u-connectLocate SW and C209 tag SW is planned to introduce periodic advertising."

Best Regards
Magnus

**Comment by perssonmagnus** [comment]
I consider this issue closed if there are no further questions.

Best Regards,
Magnus

**Comment by sfeutrier** [comment]
When is this planned ?
