### ISSUE TITLE
C209 Tag use with Conectionless Locator example

### ISSUE THREAD

**Issue by vChavezB** [u-blox/c209-aoa-tag#21]
I would like to know if its possible to use the C209 tag with the zephyr conectionless locator example?

https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/direction_finding_connectionless_rx

I tried using the example but the advertisment report for the tag reports that the periodic advertising equals 0 ms

[DEVICE]: F6:D4:16:D0:61:83 (random), AD evt type 4, Tx Pwr: 127, RSSI -64 u-blox C209 DF Tag C:1 S:1 D:0 SR:1 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 ms), SID: 255

and thus does not connect as seen by this conditional branch

https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/direction_finding_connectionless_rx/src/main.c

**Comment by jakkra** [comment]
Hi @vChavezB you need to add this to the conf. of connectionless_rx sample due to the default value of those are less than the payload we put in the ext. adv. data causing Zephyr to drop the packets.
```
CONFIG_BT_CTLR_ADV_DATA_LEN_MAX=255
CONFIG_BT_CTLR_SCAN_DATA_LEN_MAX=255
```

**Comment by vChavezB** [comment]
Thanks I just made the change and now it works
