### ISSUE TITLE
There is also no information about +UUDF

### ISSUE THREAD

**Issue by hudson203** [u-blox/c209-aoa-tag#25]
Hello! I have purchased XPLR-AOA-1 and flashed the software on c209 and c211. I confirmed that the light on c209 is blinking, and AT commands are available in s-center. However, it seems that c211 is not receiving signals from c209. There is also no information about +UUDF. Is there anything more I need to do?

Thank you.
Hudson
![image](https://github.com/u-blox/c209-aoa-tag/assets/83594910/73b30b76-a5a4-4866-be79-72852a5cc749)

**Comment by jakkra** [comment]
Hi @hudson203 
Can you first check by ticking this box to see if you get any +UUDF
![image](https://github.com/u-blox/c209-aoa-tag/assets/4318648/6d9110d2-3680-4f94-a766-e3facc4aeddf)

Edit: Can you also send `ATI9` to the tag to print it's FW version.

**Comment by hudson203** [comment]
Thank you for the quick response!
I just clicked on the checkbox, but nothing happened. Similarly, nothing appears under the tag ID.
![image](https://github.com/u-blox/c209-aoa-tag/assets/83594910/7056ecb6-fe17-4668-8db8-bcd491866e3b)

**Comment by jakkra** [comment]
@hudson203 Please send `ATI9` to the tag (if it doesn't answer, reset it (using physical button) and within 10 seconds send it again. Note you should use "no flow control" when talking with the tag.)
Make sure you flashed the latest C209 FW https://github.com/u-blox/c209-aoa-tag/releases/tag/NINA-B4-DF-TAG-2.0.1-001

**Comment by hudson203** [comment]
Thank you. When I enter ATI9, it responds as follows:
![image](https://github.com/u-blox/c209-aoa-tag/assets/83594910/e76dbdaf-c98d-4848-852f-9484375dfb7b)

**Comment by jakkra** [comment]
> Thank you. When I enter ATI9, it responds as follows: ![image](https://user-images.githubusercontent.com/83594910/285165494-e76dbdaf-c98d-4848-852f-9484375dfb7b.png)

I think you have flashed the wrong FW on C209 Tag, please re-flash with https://github.com/u-blox/c209-aoa-tag/releases/tag/NINA-B4-DF-TAG-2.0.1-001

Expected output from ATI9 is:
```
ATI9
"NINA-B4-DF-TAG-2.0.1-001","2023-04-05 15:43","2.0.1"
OK
```

**Comment by hudson203** [comment]
THANK YOU!!!!!!!!!!!!!!
I LOVE YOU 

![image](https://github.com/u-blox/c209-aoa-tag/assets/83594910/d2085d58-9331-462b-a23d-fbfb2c737b86)
![image](https://github.com/u-blox/c209-aoa-tag/assets/83594910/44fc31bc-84a8-48c1-8509-993374c3e43c)

**Comment by jakkra** [comment]
Great you got it working.
