### ISSUE TITLE
considering kits, but

### ISSUE THREAD

**Issue by sdetweil** [u-blox/c209-aoa-tag#3]
we have an application design which could benefit from the location services  AoA or AoD..
but there is something missing in the info, 
if I had the -02  kit with multiple anchors and tags,   how does one distinguish between multiple tags  at the same time?
I assume the tags are transmitting the CTE  tone on the same frequency .. and I cannot tell where I would see any of the data

with 1 or more anchors? 

is there someone I can talk to? 
 I have filled out the contact forms

**Comment by sdetweil** [comment]
running the sample location app, i dont see the behavior I would expect.. so that means I must have configured the  anchors incorrectly  top two anchors pointing down, right two anchors pointing left 

![Screenshot at 2021-12-06 11-44-55](https://user-images.githubusercontent.com/1498142/144895720-76f78408-81a9-4ac6-b4e3-1fa85a0fa76c.png)

and 
![Screenshot at 2021-12-06 11-45-23](https://user-images.githubusercontent.com/1498142/144895753-23d281c7-5971-4eb8-83b4-89390866bed7.png)

but top right(2) and right top(4) do not point concurrently to the same spot when anchor is there

top left(1),  bottom right(3)  seem relatively lost   

are the anchors supposed to be in corners?   including the bottom left (anchor entrypoint)?

can't adjust angles for anchor angle constraints

**Comment by sdetweil** [comment]
in the corners, the 4 anchors appear to be way off as they approach their angle limits
![Screenshot at 2021-12-06 12-13-00](https://user-images.githubusercontent.com/1498142/144899579-88e3f872-198f-4bdb-90be-a46bd505294c.png)

**Comment by sdetweil** [comment]
this is using fakeanchor

**Comment by perssonmagnus** [comment]
Hi Sam,

The C209 tags advertise using the Eddystone advertising format, with appended CTE, and the C211 anchor will report the Eddystone ID in the angle calculation event, see the description of +UUDF in https://www.u-blox.com/en/docs/UBX-21004616.

Regarding the Local Positioning Engine, have you filed a support case at https://portal.u-blox.com/s/? As this is related but not really part of the C209 tag SW I think this is better discussed in a case on the u-blox portal.

Thx,
-Magnus

**Comment by jakkra** [comment]
Closing as the original question has been answered and the follow up questions are not related to C209 software, other questions should go through https://portal.u-blox.com/s/
