### ISSUE TITLE
[Request] Supply different hardware file format

### ISSUE THREAD

**Issue by Cortex-0** [u-blox/c209-aoa-tag#32]
The currently supplied hardware file is in the Allegro binary format. This format is impossible to import in another ECAD software such as Altium or Eagle without having an Allegro license. The Allegro ASCII format is better suited in that regard.
Could you supply those or similar files?

**Comment by lihua-ublox** [comment]
Hello,

Thanks for your question. Here is the Allegro ASCII format of C209 pcb file. You can also extract this file by referring to
https://www.altium.com/documentation/altium-designer/allegro-import#accessing-and-running-the-importer

Please let me know if you have any more questions.
Regards,
Lihua
[Allegro_ASCII_format_of_C209_pcb _file.zip](https://github.com/user-attachments/files/17364075/Allegro_ASCII_format_of_C209_pcb._file.zip)

**Comment by Cortex-0** [comment]
Thank you for the file. 
To extract this format from the binary format you need the extracta.exe executable which is bundled with allegro and impossible to install standalone.
