### ISSUE TITLE
C209 build failed 

### ISSUE THREAD

**Issue by sdetweil** [u-blox/c209-aoa-tag#5]
Nordic sdk 1.5 is not available, only 1.6-1.8   used 1.8

Building ‘cmake_object_order_depends_target_offsets’ from solution ‘build’ in configuration ‘Common’

Building ‘zephyr/CMakeFiles/offsets.dir/arch/arm/core/offsets/offsets.c.obj’ from solution ‘build’ in configuration ‘Common’

 Compiling ‘offsets.c’

Building ‘zephyr/offsets’ from solution ‘build’ in configuration ‘Common’

Building ‘zephyr/include/generated/offsets.h’ from solution ‘build’ in configuration ‘Common’

 Combining ‘zephyr/include/generated/offsets.h’

Building ‘zephyr/CMakeFiles/offsets_h’ from solution ‘build’ in configuration ‘Common’

Building ‘zephyr/offsets_h’ from solution ‘build’ in configuration ‘Common’

Building ‘zephyr/zephyr_generated_headers’ from solution ‘build’ in configuration ‘Common’

Building ‘cmake_object_order_depends_target_app’ from solution ‘build’ in configuration ‘Common’

Building ‘app/libapp.a’ from solution ‘build’ in configuration ‘Common’

 Compiling ‘bt_adv.c’

 Compiling ‘bt_util.c’

 Compiling ‘buttons.c’

 Compiling ‘leds.c’

 Compiling ‘main.c’

 Compiling ‘production.c’

  #warning "<power/power.h> header is deprecated, use <pm/pm.h> instead" [-Werror=cpp]

  In function 'productionStart':

  implicit declaration of function 'device_set_power_state' [-Werror=implicit-function-declaration]

  'DEVICE_PM_ACTIVE_STATE' undeclared (first use in this function)

  each undeclared identifier is reported only once for each function it appears in

  In function 'disableProductionMode':

  'DEVICE_PM_OFF_STATE' undeclared (first use in this function)

  At top level:

  unrecognized command line option '-Wno-stringop-truncationw' [-Werror]

Build failed

using 1.8 of the nordic sdk, cause 1.5 is not available.

in Seeger, selected the c209 folder as the project folder

selected the 52833 in the zephry folder...

then did build solution

i gotta say, there are a ton of words in the c209 app readme that don't have any meaning for a newbie to this kind of technology.

 

what/where is

menuconfig

 

>C209 boards come pre flashed with a DFU bootloader. To build a binary that is compatible with that the 

CONFIG_FLASH_BASE_ADDRESS

 needs to be changed.

 

WHY would you make us change anything to match the bootloader type? that seems like setting the wrong expectation.

**Comment by sdetweil** [comment]
must be nrf 1.5

in Toolchain manager, select settings and uncheck show only last 3 
then scroll down to v1.5

**Comment by sdetweil** [comment]
now to figure out how to flash.. 

on mac, unable to connect to jlink (had to install manually) 
have tag plugged in on usb.

**Comment by jakkra** [comment]
> must be nrf 1.5
> 
> in Toolchain manager, select settings and uncheck show only last 3 then scroll down to v1.5

Hi, only nRF Connect SDK 1.5 is supported, it can be found in the toolchain manager like you did.
