### ISSUE TITLE
serial connect to 209 after reset

### ISSUE THREAD

**Issue by sdetweil** [u-blox/c209-aoa-tag#7]
doc says I have 10 seconds to send AT commands

try this and get error
```
AT UMLA=1

ERROR
```
with or without the + sign between AT and UMLA

the docs says for c209 
```
The AT commands that can be used to configure theinterface are described in Table 4
```

but there is no Table 4

I need a way to send stop/start advertising at any time.. (via software)

**Comment by perssonmagnus** [comment]
There should be a '+' sign, see below for the ASCII characters sent. Do you have the right line ending?
41 54 2b 55 4d 4c 41 3d 31 0d 	AT+UMLA=1.


> but there is no Table 4
Not sure what you mean. Table 4 in the [XPLR-AOA-kits user guide](https://www.u-blox.com/en/docs/UBX-21004616) is just below the sentence you are referring to, if I see correctly.
![image](https://user-images.githubusercontent.com/42796456/150865722-6c8ec409-2d8b-4165-b825-94594e22e843.png)

> I need a way to send stop/start advertising at any time.. (via software)

Do you in normal usage  want to control the C209 tag SW over the UART, and have the tag constantly connected to an MCU?
Well, you can modify the SW to add a command to do this, if you want to do it over the UART, and also make the UART interface available all the time. The use case this is designed for is slightly different, where the intention is that the C209 tag SW should be independent and maybe use the on board sensors to control when it is advertising, so you may need to modify the SW slightly to fit your intended use case.

**Comment by sdetweil** [comment]
thanks, the sensor we need is not on the tag board, so gotta do it a different way.

I tried with the +
line end not sure

table 4, 

configure the interface, see table 4. (assuming 'interface' meant UART as that was the topic at hand) 
but there are no interface configuration commands there
2 query and one transmit power.

**Comment by jakkra** [comment]
Hi @sdetweil, Line ending character is `\r`, see https://github.com/u-blox/c209-aoa-tag/blob/master/src/production.c#L165
You need to send `AT+GMM` and end with `\r` for example.

> configure the interface, see table 4. (assuming 'interface' meant UART as that was the topic at hand)
but there are no interface configuration commands there
2 query and one transmit power.

That's a missunderstanding, there is only UART interface and those 3 commands.

**Comment by sdetweil** [comment]
thanks... now on to connecting to the 209 via uart,,

the doc seems pretty clear (table 3).. except when I look  at the board, the labeling says 
(left edge, usb down, component side up) 
says GPIO 27,17,38(maybe 36), 37, 34,35,36

![tag face](https://user-images.githubusercontent.com/1498142/150995317-ec8e5aec-194d-48c3-b40c-ef338e6879f2.jpg)

docs says otherwise
![Screenshot at 2022-01-25 08-22-04](https://user-images.githubusercontent.com/1498142/150994519-4d8ad7b5-846f-4459-95aa-8287ddd37b9a.png)

but none of the doc listed GPIO pins are listed as on the board. (or even could be on the board)

**Comment by sdetweil** [comment]
and there are 10 GPIO pins listed in the doc, and only 8 listed on the board

**Comment by sdetweil** [comment]
@jakkra   on line end.. 
the mac serial tool  provides cr/lf as a choice, but doesn't document the default behaviour

**Comment by sdetweil** [comment]
any idea where I could get more info?

**Comment by jakkra** [comment]
I don't use Mac so cannot help with that, I guess there are many serial terminal applications you can try, personally I use Putty, Realterm, Teraterm, but don't know if any of them are on Mac.

**Comment by sdetweil** [comment]
sorry, i have moved on from line end to trying to figure out what board pins/sockets to use..

starts with this 

now on to connecting to the 209 via uart,,

**Comment by perssonmagnus** [comment]
Hi,
The list of C209 GPIO  pins in Table 3 of the [XPLR-AOA kits user guide](https://www.u-blox.com/en/ubx-viewer/view/XPLR-AOA-Explorer-kits_UserGuide_UBX-21004616?url=https%3A%2F%2Fwww.u-blox.com%2Fsites%2Fdefault%2Ffiles%2FXPLR-AOA-Explorer-kits_UserGuide_UBX-21004616.pdf) is not a complete list of pins going to/from the module, this is a helper list for accessing stuff like the sensors, buttons and LEDs. It is not a full list and it does not mean that these pins are accessible on the board. 

There are complete C209 schematics in appendix D, where you can see that for example the UART pins are available as test points, if it was the UART pins you were looking for.

**Comment by sdetweil** [comment]
thanks.. not an electrical engineer, so hard to discern what all that schematic  means

but net, we will have to provide power and serial thru usb port..  production connection to test points wouldn't work. 

do you know anyone that can answer 211 board questions?
last post here
https://portal.u-blox.com/s/question/0D52p0000Bz6kIcCQI/c211-connection-setup?t=1643294813670

**Comment by perssonmagnus** [comment]
Questions answered.

**Comment by sdetweil** [comment]
ok, 211 is easier than 209

I need a full time serial port connection to the 209 from my arduino nano board with my software, so i can control the 209. (thru enhanced AT commands)
